# Generated by Django 2.1 on 2018-08-20 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mile1', '0004_auto_20180818_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='images_added',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='image',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mile1.Restaurant'),
        ),
    ]
